### ISSUE TITLE
Transaction View

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/telos-wallet#147]
- [ ] As a user, I want to be able to view my transaction history, including the type of transaction (e.g., send, receive, swap), the addresses involved, the transaction hash with a link to Telos Scan, the amounts involved in USD and tokens (when available), the date and time of the transaction, and the gas fee.
- [ ] As a user, I want the Telos EVM Wallet to display transaction types using icons, to make them more easily recognizable.
- [ ] As a user, I want to see the relative time (e.g. 10 minutes ago) of my transaction when I hover over the date and time it was executed
- [ ] As a user, I want to be able to paginate through my transactions

## Figma
https://www.figma.com/file/eIpbnt6vqwqptEbZWtwO8Y/v0.3?node-id=223%3A1853&t=JzCFOo3I7ogrKlS5-1

**Comment by karynemayer** [comment]
duplicate of https://github.com/telosnetwork/telos-wallet/issues/167
