### ISSUE TITLE
EVM Wallet - Add Safepal wallet support (Injected provider)

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/telos-wallet#422]
## Overview
We want our users that have Safepal wallet to be able to connect to the Telos Wallet

## Links
https://devdocs.safepal.com/Connect-wallet/Mobile/walletconnet.html#evm-webapp

https://www.safepal.com/en/download
## Acceptance Criteria
Users on desktop using SafePal Extension can connect to wallet and use all its features.
Users on desktop can use walletconnect to connect their safepal mobile wallet with the desktop site.
Users on mobile using walletconnect can use their browser and their safepal mobile wallet to connect to the mobile site.
Users on mobile using SafePal app can connect to wallet and use all its features 

  NOTE: We do not need to be a dapp on safepal to test this but:
     1. Wallet page and deployments on netlify sometimes do not work, being a dapp would help us for main site, not for deployed.
     2. The testnet is not added as a network, I made the request for them to add it on their telegram with us.

**Blocked by https://github.com/telosnetwork/telos-wallet/issues/450**

## Tasks
Desktop
- [x] extension support via WalletConnect (connect, send transactions, etc)
- [ ] extension support via direct SafePal button on desktop
- [ ] handle conflicting/multiple providers (tracking and/or notifications)

Mobile
- [x] connect with mobile app via WalletConnect
- [ ] Direct link on mobile for SafePal.
- [ ] send transactions (WC)
- [ ] chain switching (WC)

**Comment by Viterbo** [comment]
Form to add a Dapp into the SafePal Dapp whitelist so we can be selected from inside the Wallet:
https://docs.google.com/forms/d/e/1FAIpQLSdBvCFSbuD2D5a8rlmrnQtBDgS1v-3yoJ5Lb2zPyfVFYP3hww/viewform
