### ISSUE TITLE
Add walletconnect telos cloud wallet support on Telos Wallet

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/telos-wallet#577]
**Background**
Integrate WalletConnect support into our system to work seamlessly with ORE ID technology. This will require communication with the Aikon team for guidance due to limited documentation.

Contact:
Reach out to @pmjanus on Telegram for any queries.

Resources:

[ORE ID Documentation](https://docs.oreid.io/)
[App ID Generation](https://ore-id.telos-docs.pages.dev/evm/cloud-wallet/getting-started)

**Acceptance Criteria:**

- [ ] Ensure all wallet functions (send, receive, wrap, unwrap, and optional staking) are functional when cloud wallet is connected on desktop and mobile.
- [ ] Update the Telos Cloud Wallet icon on the login page. Get from pmjanus
- [ ] Obtain and update the logo for the WalletConnect view within the Telos Cloud Wallet. get from pmjanus

**Sub-Tasks:**

- [ ] Create documentation outlining the integration process for future reference by other teams.

- blocked by web3modal-connector-oreid package dependency on react dependencies via wagmi. Need a vanilla js or vue implementation in order to implement.

**Comment by pmjanus** [comment]
https://docs.walletconnect.com/web3modal/about WebModal 3 might unblock this.

**Comment by donnyquixotic** [comment]
Revisitng this, unless I'm mistaken, the wallet connect integration instructions are for a specific _user_ not an _app_. See [Wallet Connect Ore ID](https://docs.oreid.io/ore-id/build/features/wallet-connect/connect-to-a-service) documentation.
