### ISSUE TITLE
Add ORE ID support for native

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/telos-wallet#579]
## Overview
Implement ORE ID ual to implement telos cloud wallet for native users

## Links
https://docs.oreid.io/ore-id/build/integration/ual
https://docs.oreid.io/ore-id/blockchains/eosio/get-eos-account-info-and-balance

## Tasks

- [x] install and implement oreid ual package for native telos cloud wallet
- [x] generate app id (if required)

## Testing
testnet
- [x] account creation
- [x] send transaction
- [x] buy resources
- [x] send to evm

mainnet
- [x] account creation*
- [x] send transaction
- [x] buy resources
- [x] staking
- [x] generate linked evm adress 
- [x] send to evm
- [x] withdraw from evm to native
