### ISSUE TITLE
Implement back up query & notification for stale NFT indexer data

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/telos-wallet#659]
**Describe the bug**
If the indexer data is stale, nft ownership/quantity may not be accurate. We should implement an indexer health check and backup queries where possible, to fetch current data. 

**To Reproduce**
1. Check if indexer data is stale by querying the /v1/health endpoint
2. If indexer data is stale (or hardcode stale health check result) , perform an NFT transaction
3. See nft ownership fail to update and ability to send again

**Expected behavior**
User should be notified on collection inventory page (see Teloscan for stale data notification) if data is stale and a backup query should be performed to update individual NFT data on the details page

**Tasks**

- [x] Notification of stale data (NFT inventory page)
- [x] Use ethers to query 721 contract for `ownerOf` to update 
- [x] Use ethers to query 1155 contract for `balanceOf` to update quantity

**Additional context**
- there is already a health check in code and backup for balances
