### ISSUE TITLE
Update branding

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/telos-wallet#678]
**Description**
Update theme using new logos & colors

**Tasks**

- [x] Update Telos Wallet logo svg
- [ ] token logo- staking
- [ ] token logo - teloscan dropdown link
- [ ] token logo - favicon
- [ ] Update colors/theme

**Blockers**

- [x] Telos Wallet logo svg
- [ ] Theme colors

**Resources**
https://www.telos.net/community-resources
https://github.com/telosnetwork/token-list
